apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  selector:
    app: catalogue
  ports:
    - protocol: TCP
      port: 80  # Port on the service
      targetPort: 8080  # Port on the pod (your application should be listening on this port)
  type: ClusterIP