apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 80  # Port on the service
      targetPort: 8089  # Port on the pod (your application should be listening on this port)
  type: ClusterIP